sequenceDiagram
  participant R as Repo
  participant G as Gateway
  participant B as Bridge
  participant D as DDP

  R ->> G: Object Restore
  G ->> B: Get Deposited Content
  B -->> G: 200 Ok
  G ->> B: Restore Content
  D ->> B: List Restores
  B -->> D: 200 Ok
  Note over D: DDP - Bridge <br/> Staging Workflow <br/> (with TTL)
  D ->> B: Complete Restore
  Note over B: Validate Checksums

  G ->>+ B: Restore Status
  B -->> G: STAGED_FOR_RESTORE

  G ->> B: Get Restored Content
  B -->>- G: ok

  R ->> G: Get Object
  G -->> R: Ok

